"""SSZ merkleization primitives (M3): zero_hash table, incremental
merkle-stack accumulator, and mix_in_length.

Implements docs/design/003-ssz-verifier.md §5.5. These are the building
blocks needed to merkleize a chunk stream (e.g. M1's 512-pubkey
`SyncCommittee` install-time check, design doc §2.7) without ever buffering
a full leaf layer, which is impossible above 128 leaves on the AVM (§2.8:
16,384 bytes for a 512-leaf layer exceeds the 4,096-byte AVM value cap).
"""
import typing

from algopy import Bytes, UInt64, subroutine, urange, op

# ---------------------------------------------------------------------------
# zero_hash: precomputed table, NOT on-demand recomputation.
#
# Design doc §5.5 / checklist item 6: on-demand recomputation of
# zero_hash(i) = sha256(zero_hash(i-1) || zero_hash(i-1)) measured at 67.5
# budget per level (§2.7); a table lookup is a few opcodes. This table holds
# the first 64 values (depths 0..63) as program constants -- 64 * 32 = 2,048
# program bytes, affordable within the 8,192-byte cap (§5.5) -- which is far
# beyond any real SSZ depth this project needs (the deepest published gindex
# is 221184, depth 17; the deepest single-app-call-safe depth is 10, §2.6).
#
# Kept as a plain `str` module constant (Puya only allows literal int/str/
# bytes at module scope, not constructed `algopy` values) and turned into a
# `Bytes` program constant inside `zero_hash` itself via `Bytes.from_hex`,
# which Puya folds to a single pushbytes -- there is no per-call hex-decode
# at runtime.
#
# _ZERO_HASH_TABLE_HEX, decoded, is _ZERO_HASH_TABLE[32*i : 32*i+32] ==
# zero_hash(i) for i in 0..63. Generated by: zh[0] = 32 zero bytes;
# zh[i] = sha256(zh[i-1] + zh[i-1]).
_ZERO_HASH_TABLE_HEX: typing.Final[str] = (
    "0000000000000000000000000000000000000000000000000000000000000000F5A5FD42D16A20302798EF6ED309979B43003D2320D9F0E8EA9831A92759FB4BDB56114E00FDD4C1F85C892BF35AC9A89289AAECB1EBD0A96CDE606A748B5D71C78009FDF07FC56A11F122370658A353AAA542ED63E44C4BC15FF4CD105AB33C536D98837F2DD165A55D5EEAE91485954472D56F246DF256BF3CAE19352A123C9EFDE052AA15429FAE05BAD4D0B1D7C64DA64D03D7A1854A588C2CB8430C0D30D88DDFEED400A8755596B21942C1497E114C302E6118290F91E6772976041FA187EB0DDBA57E35F6D286673802A4AF5975E22506C7CF4C64BB6BE5EE11527F2C26846476FD5FC54A5D43385167C95144F2643F533CC85BB9D16B782F8D7DB193506D86582D252405B840018792CAD2BF1259F1EF5AA5F887E13CB2F0094F51E1FFFF0AD7E659772F9534C195C815EFC4014EF1E1DAED4404C06385D11192E92B6CF04127DB05441CD833107A52BE852868890E4317E6A02AB47683AA75964220B7D05F875F140027EF5118A2247BBB84CE8F2F0F1123623085DAF7960C329F5FDF6AF5F5BBDB6BE9EF8AA618E4BF8073960867171E29676F8B284DEA6A08A85EB58D900F5E182E3C50EF74969EA16C7726C549757CC23523C369587DA7293784D49A7502FFCFB0340B1D7885688500CA308161A7F96B62DF9D083B71FCC8F2BB8FE6B1689256C0D385F42F5BBE2027A22C1996E110BA97C171D3E5948DE92BEB8D0D63C39EBADE8509E0AE3C9C3876FB5FA112BE18F905ECACFECB92057603AB95EEC8B2E541CAD4E91DE38385F2E046619F54496C2382CB6CACD5B98C26F5A4F893E908917775B62BFF23294DBBE3A1CD8E6CC1C35B4801887B646A6F81F17FCDDBA7B592E3133393C16194FAC7431ABF2F5485ED711DB282183C819E08EBAA8A8D7FE3AF8CAA085A7639A832001457DFB9128A8061142AD0335629FF23FF9CFEB3C337D7A51A6FBF00B9E34C52E1C9195C969BD4E7A0BFD51D5C5BED9C1167E71F0AA83CC32EDFBEFA9F4D3E0174CA85182EEC9F3A09F6A6C0DF6377A510D731206FA80A50BB6ABE29085058F16212212A60EEC8F049FECB92D8C8E0A84BC021352BFECBEDDDE993839F614C3DAC0A3EE37543F9B412B16199DC158E23B544619E312724BB6D7C3153ED9DE791D764A366B389AF13C58BF8A8D90481A467657CDD2986268250628D0C10E385C58C6191E6FBE05191BCC04F133F2CEA72C1C4848930BD7BA8CAC54661072113FB278869E07BB8587F91392933374D017BCBE18869FF2C22B28CC10510D9853292803328BE4FB0E80495E8BB8D271F5B889636B5FE28E79F1B850F8658246CE9B6A1E7B49FC06DB7143E8FE0B4F2B0C5523A5C985E929F70AF28D0BDD1A90A808F977F597C7C778C489E98D3BD8910D31AC0F7C6F67E02E6E4E1BDEFB994C6098953F34636BA2B6CA20A4721D2B26A886722FF1C9A7E5FF1CF48B4AD1582D3F4E4A1004F3B20D8C5A2B71387A4254AD933EBC52F075AE229646B6F6AED19A5E372CF295081401EB893FF599B3F9ACC0C0D3E7D328921DEB59612076801E8CD61592107B5C67C79B846595CC6320C395B46362CBFB909FDB236AD2411B4E4883810A074B840464689986C3F8A8091827E17C32755D8FB3687BA3BA49F342C77F5A1F89BEC83D811446E1A467139213D640B6A74F7210D4F8E7E1039790E7BF4EFA207555A10A6DB1DD4B95DA313AAA88B88FE76AD21B516CBC645FFE34AB5DE1C8AEF8CD4E7F8D2B51E8E1456ADC7563CDA206F6BFE8D2BCC4237B74A5047058EF455339ECD7360CB63BFBB8EE5448E6430BA04A7F23CE9181740DC220C814782654FEE6ACEB9F1EC9222C4E2467D0AB1680837AEF9476C89590A2C8CC9B3B74F4967C757C49D9866A44BACF21FA2ED675DDFA29A42BCAD82F6A9E41284D808EAD319F29F3B08209D680F0E2CE71510D071E205D1A66D354A67B9CF179571D8E5F97792716E8DD4EC44196839A3F7C6B74F8BACFAFA3025F2F89509C2C71C74FBA0CD92858EF49B0780FB5479746C8A9BFCB3463334A7C1E7F6705AA6011A6A949645016DB4ACDE0CA9ABD66DC79D82664230560796FD75664FAEF744EE4E52D7271E2BBB769F91ED6F9B74D8B694F56606852C7BA3AE4A417FE8545B142BC89F4ADCD7AE13941CBAB7750B83E9F0A66D16BE64788FAFCC4AA520399ADBAED195F8B12C4EB31EC10168E50AABC659A6AEA516DCE833D7A67160E68BF4C9044A53077DF2727AD00CF36F4949C7B681A912140CBB309EABF095DC6714F9F4D864BBA5AFFAE0B35AE2F5E3565BCC3A47B212767701226A8EBEFA288665A644A50273335EFBB610510F241B5B720C8A368D59A69A5D41ABFD995425827625938131AF0C4F33FE0BD4688C222C21FA9DA8E89CAA03F8442C642EF50FA1A667A6E6D105C77C5CC3FEC8D7AA2570CF1A3077B503C38069A0A08DFC9B42D96C2DE19B6D127B8AE136DDCF3E5AD0DCE422C45A56F61F6A747D348382AF096DBE0BF086C7BB39B2A2C0BC36B621AB0C738E9885D731D817403AB134751D191269026C86994EAA8B43A83B4AD1F6D0E77381C4E2974AFBC8F69A7452611DB2D23EAE26F9BDBB88958EF44C64D0FE987BE9F726ADF938F50F6C725C7F816037BFE452CD1E7BA35AC47EDCB49A9A2B27AECA70DCE483CB7DED1F2CEA1AF51FB28B62887C39998AC9FEF4DFDEDA1F07E071BA558A173AFD06CBC3FF1D59F98B6C551D95089357057D5C8BE26402279E9DF0B1DF1A10B72BF3927F2F8A181F7C99DD215A7529BFE296A9603A1446737186D21AEB8BC7AE59E1FD21ECC502C9B1145F3950CB7D3E3842446F81A4F0DF1DF537CEE139EF64EA984BD9"
)

_ZERO_HASH_TABLE_DEPTH = 64


@subroutine
def zero_hash(depth: UInt64) -> Bytes:
    """Root of an all-zero subtree of the given depth.

    `zero_hash(0)` is 32 zero bytes. `zero_hash(i) = sha256(zero_hash(i-1) ||
    zero_hash(i-1))`. This is a table lookup into the precomputed
    `_ZERO_HASH_TABLE_HEX` program constant, not a recomputation -- see the
    module docstring above for why that distinction is load-bearing, not
    stylistic.
    """
    assert depth < _ZERO_HASH_TABLE_DEPTH, "zero_hash: depth exceeds precomputed table size (64)"
    table = Bytes.from_hex(_ZERO_HASH_TABLE_HEX)
    offset = depth * 32
    return table[offset : offset + 32]


@subroutine
def merkleize_stack_push(state: Bytes, filled: UInt64, chunk: Bytes) -> tuple[Bytes, UInt64]:
    """Push one 32-byte chunk into an incremental-merkleization accumulator.

    `state` is a packed stack of up to `depth+1` 32-byte nodes (caller must
    pre-size it to `32 * (depth + 1)` bytes, e.g. 320 bytes / 10 slots for a
    512-leaf tree); `filled` is a bitmask of which stack levels currently
    hold a carried partial node. This is the standard incremental/streaming
    binary-counter merkle accumulator (the same shape as the Ethereum
    deposit contract's incremental Merkle tree): pushing behaves like a
    binary counter increment, carrying (combining via `sha256`) through
    every currently-occupied level until it reaches an empty one. After `n`
    sequential pushes from an empty state, `filled` equals the binary
    representation of `n`.

    MUST be used instead of buffering a layer -- a full 512-leaf layer is
    16,384 bytes and exceeds the AVM's 4,096-byte value cap (design doc
    §2.8). Scratch requirement is `depth+1` slots of 32 bytes.

    Call `merkleize_stack_finalize` once all chunks are pushed to combine
    the accumulator into the root of a subtree of a chosen target depth,
    padding any never-filled level with `zero_hash(level)` -- never with 32
    zero bytes at every level (design doc §7.4: padding a level-i gap with
    `zero_hash(0)` instead of `zero_hash(i)` silently yields a wrong root,
    and this bug is invisible whenever the chunk count is a power of two).

    Returns the updated `(state, filled)`.
    """
    node = chunk
    level = UInt64(0)
    f = filled
    while op.getbit(f, level):
        sibling_offset = level * 32
        sibling = state[sibling_offset : sibling_offset + 32]
        node = op.sha256(sibling + node)
        f = f ^ (UInt64(1) << level)
        level += 1

    write_offset = level * 32
    assert write_offset + 32 <= state.length, "merkleize_stack_push: state too small for this many chunks"
    new_state = state[0:write_offset] + node + state[write_offset + 32 : state.length]
    new_filled = f | (UInt64(1) << level)
    return new_state, new_filled


@subroutine
def merkleize_stack_finalize(state: Bytes, filled: UInt64, depth: UInt64) -> Bytes:
    """Combine a `merkleize_stack_push` accumulator into the root of a
    subtree of the given target `depth` (`ceil(log2(N))` for `N` chunks).

    Every level that was never filled (i.e. every push chain that never
    grew that tall) is padded with `zero_hash(level)`, matching SSZ's
    zero-padding rule for non-power-of-two lengths (design doc §7.4). This
    is the same algorithm as the Ethereum deposit contract's `get_root`,
    generalized to an arbitrary `depth` and an explicit `filled` bitmask in
    place of a running deposit count (the two coincide for sequential
    pushes from empty, see `merkleize_stack_push`).

    Not itself named in design doc §5.5's three-subroutine list, but
    required to turn `merkleize_stack_push` into a usable end-to-end
    merkleization primitive -- `zero_hash` and `merkleize_stack_push` alone
    only build the accumulator, they never close it out into a single root.

    `depth == 0` is a special case, analogous to `compute_merkle_branch_root`'s
    own depth-0 convention (design doc §7.1): a depth-0 subtree has exactly
    one leaf slot, so its "root" IS that leaf (`state[0]`) if one was pushed,
    or `zero_hash(0)` if none was. The general loop below runs zero
    iterations at depth 0 and would otherwise always return `zero_hash(0)`
    regardless of `filled`, silently discarding a real pushed chunk.
    """
    if depth == 0:
        if op.getbit(filled, UInt64(0)):
            return state[0:32]
        return zero_hash(UInt64(0))

    node = zero_hash(UInt64(0))
    for level in urange(depth):
        if op.getbit(filled, level):
            sibling_offset = level * 32
            sibling = state[sibling_offset : sibling_offset + 32]
            node = op.sha256(sibling + node)
        else:
            node = op.sha256(node + zero_hash(level))
    return node


@subroutine
def mix_in_length(root: Bytes, length: UInt64) -> Bytes:
    """`sha256(root || uint256_le(length))` -- the SSZ `List`/`Bitlist` tail.

    `hash_tree_root` of an SSZ `List`/`Bitlist` mixes the runtime length
    into the merkleized-and-padded-to-type-limit root (design doc §2.11,
    §7.4-item-3): the tree itself must be sized from the type limit `N`,
    NOT the runtime length -- using the runtime length to size the tree is
    a classic SSZ bug that yields wrong roots for every non-full list.

    `length` must be encoded 32-byte LITTLE-endian. `op.itob` produces
    8-byte BIG-endian, so it is byte-reversed here and right-padded with 24
    zero bytes. Getting this endianness wrong yields a wrong root at
    identical budget (§2.11) -- it will never show up as a cost regression.
    """
    length_be = op.itob(length)
    length_le = Bytes()
    for one_byte in reversed(length_be):
        length_le += one_byte
    length_le_32 = length_le + op.Global.zero_address.bytes[0:24]
    return op.sha256(root + length_le_32)
